volumes:
  sqlserver_data:

services:
  hydraapi:
    image: ${DOCKER_REGISTRY-}hydraapi
    build:
      context: .
      dockerfile: ../HydraApi/HydraApi/Dockerfile

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123#Secret"
      MSSQL_LOGGING: "verbose"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./db_backups:/backup
  
  # mssql.configurator:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   volumes:
  #     - ./init:/docker-entrypoint-initdb.d
  #   depends_on:
  #     msssql:
  #       condition: service_healthy
  #   command: >
  #     bash -c '
  #     /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P ${Sa_Password:-123#Secret} -d master -i docker-entrypoint-initdb.d/mssql-init.sql;
  #     echo "All done!";
  #     '